# Generated by Django 3.1.1 on 2020-10-01 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_auto_20201001_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='oner',
            new_name='owner',
        ),
    ]
